target-version = "py310"

[lint]
select = [
    "E4",
    "E7",
    "E9",
    "F",
    "I",
    "ERA",
    "C4",
    "S",
    "B",
    "PIE",
    "Q",
    "RET",
    "SLF",
    "RUF",
    "N",
    "FURB",
    "TC",
]
ignore = ["B904", "N818"]
